### ISSUE TITLE
Zero distinct states for seemingly superfluous action `MuxStateWait`

### ISSUE THREAD

**Issue by lemmy** [GerardoGran/gemini-tla-verification#5]
The sub-actions `EXEC_LINKMANAGER_CHECK` and `EXEC_LINKMANAGER_SWITCH` appear independently of `MuxStateWait` in `Next`.

https://github.com/GerardoGran/gemini-tla-verification/blob/a9e46233ff86cae93bbcd8556a45d0e0f2416f56/gemini.tla#L187-L192

<img width="832" alt="Screen Shot 2022-09-06 at 10 14 23 AM" src="https://user-images.githubusercontent.com/88777/188698735-3e7f82d7-c2b4-4133-be58-8c3b9034a449.png">

**Comment by zjswhhh** [comment]
In implementation, we introduced "wait", trying not to request another SWITCH/CHECK when there is one ongoing request, (so no CHECK/SWICH action when MuxState == Wait). 

In the specs, I see SWITCH/CHECK is only triggered in `MuxStateStandby`, `MuxStateActive`, `MuxStateUnkown`, so yes there is no true difference if we remove `MuxStateWait` in specs. Markus's analysis proved it too. 

@GerardoGran - it's up to you if you want to remove it.

**Comment by GerardoGran** [comment]
Since MuxStateWait now resends the check request it creates distinct states now 👍
